name: pikseltesisat
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  #core
  go_router: ^14.4.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  easy_localization: ^3.0.7
  cloud_firestore: ^5.4.5
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  firebase_storage: ^12.3.5
  collection: ^1.18.0
  image_picker: ^1.1.2
  #ui
  firebase_ui_firestore: ^1.7.0
  flutter_spinkit: ^5.2.1
  skeletonizer: ^1.4.2
  flutter_advanced_drawer: ^1.3.7
  phone_form_field: ^10.0.1
  circular_menu: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  go_router_builder: ^2.7.1
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/localization/
    - assets/images/
