name: pikseltesisat
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  #core
  go_router: ^14.4.1
  equatable: ^2.0.5
  flutter_bloc: ^9.1.0
  easy_localization: ^3.0.7
  cloud_firestore: ^5.4.5
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  firebase_storage: ^12.3.5
  collection: ^1.18.0
  image_picker: ^1.1.2
  # kartal: ^4.1.0
  get_it: ^8.0.3
  injectable: ^2.3.2
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  rps: ^0.7.0
  #ui
  firebase_ui_firestore: ^1.7.0
  flutter_spinkit: ^5.2.1
  skeletonizer: 
    git:
      url: https://github.com/tahsin-emre/skeletonizer.git
      ref: main
  flutter_advanced_drawer: ^1.3.7
  phone_form_field: ^10.0.1
  circular_menu: ^4.0.0
  toastification: ^3.0.2
  easy_date_timeline: ^2.0.6
  flutter_speed_dial: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  go_router_builder: ^2.7.1
  very_good_analysis: ^7.0.0
  injectable_generator: ^2.4.1
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
  assets:
    - assets/localization/
    - assets/images/
    - assets/.env
