name: pikseltesisat
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  #core
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  easy_localization: ^3.0.7
  cloud_firestore: ^5.4.5
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  firebase_storage: ^12.3.5
  collection: ^1.18.0
  image_picker: ^1.1.2
  #ui
  flutter_spinkit: ^5.2.1
  skeletonizer: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
