// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDDYkBTefwoVMsmeuWa96Wvw-E5P42FHo',
    appId: '1:808781760772:web:6ffefec60c92e632bea851',
    messagingSenderId: '808781760772',
    projectId: 'piksel-tesisat',
    authDomain: 'piksel-tesisat.firebaseapp.com',
    storageBucket: 'piksel-tesisat.firebasestorage.app',
    measurementId: 'G-NQLP0C09EG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_OnZFoVVj2yYfiK9gl1rNWkAFlWXs6gY',
    appId: '1:808781760772:android:18549fdb4539104dbea851',
    messagingSenderId: '808781760772',
    projectId: 'piksel-tesisat',
    storageBucket: 'piksel-tesisat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiq7mCX4NH6iI4t5iidakdqg5LhN4NUHQ',
    appId: '1:808781760772:ios:2ed616ff85880513bea851',
    messagingSenderId: '808781760772',
    projectId: 'piksel-tesisat',
    storageBucket: 'piksel-tesisat.firebasestorage.app',
    iosBundleId: 'com.tahsinemre.pikseltesisat',
  );
}
